/** Local comparison page. Receipts are generated by the production renderers. */
export function billStyleGallery(): string {
  const styles = [
    ["classic", "Classic", "Receipt mono", "Familiar counter-bill layout with dotted rules."],
    ["modern", "Modern", "Bold sans serif", "Strong headings, clean dividers and a prominent total."],
    ["heritage", "Heritage", "Traditional serif", "Elegant letterforms, double rules and a quieter finish."],
    ["compact", "Compact", "Space-saving sans serif", "Tighter spacing and a clear hierarchy for busy counters."],
  ];
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Restaurant bill styles · ForkFlow</title><style>
    *{box-sizing:border-box}body{margin:0;background:#eeeee9;color:#202820;font:14px/1.5 Arial,sans-serif}
    main{max-width:1060px;margin:auto;padding:36px 28px 48px}header{max-width:720px}.eyebrow{text-transform:uppercase;letter-spacing:2px;font-size:11px;font-weight:bold;color:#51604f}
    h1{font-size:36px;line-height:1.1;letter-spacing:-1.4px;margin:10px 0 14px}p{margin:0;color:#515a51}
    .controls{display:flex;flex-wrap:wrap;gap:18px;margin:24px 0 10px;padding:18px 0;border-block:1px solid #c9cec4}
    label{display:grid;gap:6px;font-size:12px;font-weight:bold}select{min-width:215px;max-width:100%;padding:10px;background:#fff;border:1px solid #7c8778;border-radius:4px;font:14px Arial;color:#202820}
    .note{font-size:12px;margin-bottom:28px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:28px;align-items:start}
    article{min-width:0}.card-heading{display:flex;gap:12px;align-items:center;margin-bottom:9px}.number{border:1px solid #9aa393;border-radius:50%;width:29px;height:29px;display:grid;place-items:center;font-size:11px}
    h2{font-size:22px;letter-spacing:-.5px;margin:0}small{margin-left:auto;color:#51604f;font-size:11px}.description{font-size:12px;margin-bottom:12px}
    iframe{display:block;width:100%;height:920px;border:1px solid #c9cec4;background:#fff}.links{display:flex;gap:18px;padding:12px 0}
    a{color:#244c30;font-weight:bold;font-size:12px;text-underline-offset:3px}:focus-visible{outline:3px solid #61834f;outline-offset:3px}
    footer{margin-top:32px;border-top:1px solid #c9cec4;padding-top:16px;font-size:12px;color:#515a51}
    @media(max-width:760px){main{padding:24px 16px}.grid{grid-template-columns:1fr}h1{font-size:31px}.controls{gap:12px}label{flex:1;min-width:0}select{min-width:0;width:100%}small{font-size:10px}}
  </style></head><body><main><header><div class="eyebrow">ForkFlow · Print collection</div><h1>A bill for every kind of table.</h1>
  <p>Four restaurant bill styles, with the same clear item details, accurate totals and payment information. Choose yours in the app under <strong>Settings → Bill style → Save</strong>.</p></header>
  <div class="controls"><label>Bill sample<select id="tax"><option value="inclusive">Tax included · payment due</option><option value="exclusive">GST added · paid</option></select></label>
  <label>Print format<select id="format"><option value="">Preview / A4 PDF</option><option value="-80mm">80 mm thermal</option><option value="-58mm">58 mm thermal</option></select></label></div>
  <p class="note" id="format-note">Preview/PDF uses each style’s typeface. Open a bill to print or save it as a PDF.</p>
  <div class="grid">${styles.map(([id, name, font, description], index) => `<article data-style="${id}"><div class="card-heading"><span class="number">0${index + 1}</span><h2>${name}</h2><small>${font}</small></div><p class="description">${description}</p><iframe title="${name} bill preview" src="bill-${id}-inclusive.html"></iframe><div class="links"><a class="open" href="bill-${id}-inclusive.html" target="_blank">Open bill ↗</a><a href="bill-${id}-upi.html" target="_blank">With payment QR ↗</a></div></article>`).join("")}</div>
  <footer>Sample restaurant details and payment address are for layout review only. Each new bill saves its style; historic bills retain their original design. Physical thermal output depends on the printer.</footer>
  </main><script>
    const tax = document.querySelector('#tax'), format = document.querySelector('#format');
    function resize(frame) { frame.style.height = ((frame.contentDocument?.documentElement.scrollHeight || 920) + 4) + 'px'; }
    document.querySelectorAll('iframe').forEach(frame => { frame.addEventListener('load', () => { frame.style.height = '100px'; resize(frame); }); });
    function update() {
      document.querySelectorAll('article').forEach(card => {
        const url = 'bill-' + card.dataset.style + '-' + tax.value + format.value + '.html';
        const frame = card.querySelector('iframe'); frame.style.height = '100px'; frame.src = url; card.querySelector('.open').href = url;
      });
      document.querySelector('#format-note').textContent = format.value ? 'Thermal previews use the printer’s built-in font. Alignment, emphasis and spacing reflect the chosen style.' : 'Preview/PDF uses each style’s typeface. Open a bill to print or save it as a PDF.';
    }
    tax.addEventListener('change', update); format.addEventListener('change', update);
    window.addEventListener('resize', () => document.querySelectorAll('iframe').forEach(frame => { frame.style.height = '100px'; resize(frame); }));
  </script></body></html>`;
}
